###服务启动端口号
server:
  port: 8000
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: SpringBoot4DB
  mail:
    host: smtp.qq.com
    username: 1078058570@qq.com
    password: ipauaqqgkfmnbaba
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#  jpa:
#    database: oracle
#    show-sql: true
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@ip:1521:dev
#    username: app_outpay
#    password: Test01C8!654321